Unittest
CZ-NIC/envelope pull request #38
Opened 2024-08-22 12:10 UTC by adidas-official

Fixed an issue with loading password protected cert and updated some expected values in unittests to correct ones. Some minor differences in the signatures could be because of the switch from M2Crypto to PyCA cryptography library and each generate slightly different first line. Signatures were verified with openssl in terminal and every signature was valid.

2024-08-28 12:20 UTC, adidas-official commented
Updated tests to check for values following current standards. All changes were manually tested if the messages can still be decrypted or verified. Value in tests smime_key_cert_together* could most likely also be modified, but I was not able to come up with the command to verify the decryption.

2024-09-11 10:56 UTC, adidas-official commented
All tests are now success. Two tests were rewritten to use M2Crypto for decrypting, since PyCA cryptography does not support decrypting SMIME envelope directly.

2024-10-04 14:49 UTC, e3rd requested changes
Rebase the pull request to a single (or more) commit (get rid of the WIP commits) (if not, I'll squash it myself later to a single commit). Close other PRs.

2024-10-04 14:49 UTC, e3rd commented on .gitignore
> +.vscode
Please put this into your .git/info/exclude file, I've been told once this is the right way of handling the files that does not relate.

2024-10-04 14:49 UTC, e3rd commented on envelope/envelope.py
> +            self._smtp.quit() #
trailing #

2024-10-04 14:49 UTC, e3rd commented on test_.py
> +    def bash(self, *cmd, file: Path = None, piped=None, envelope=True, env=None, debug=True, decode=True):
why changing debug to true? :)

2024-10-04 14:49 UTC, e3rd commented on test_.py
> +        import re
put the import to the module start

2024-10-04 14:49 UTC, e3rd commented on test_.py
> +    # def test_smime_key_cert_together(self):
why commented? is there an alternative somewhere?

2024-10-07 08:10 UTC, closed without merging